<style>
	/* qr code */
	.content {
		width: 41%;
		margin-left: 8.7rem;
		display: flex;
		flex-direction: column;
		align-items: flex-start;
		justify-content: center;
	}

	.input-qr {
		width: 100%;
		padding: 15px 10px;
		border: 1.5px solid rgb(52, 51, 51);
		font-size: 17px;
		outline: none;
		border: 1px solid black;
	}

	.input-qr:focus {
		border: 1.7px solid rgb(4, 84, 213);
	}

	#qrcode {
		margin-top: 30px;
	}
	/* end qr code */
</style>

<!-- <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script> -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsbarcode/3.11.3/JsBarcode.all.min.js"></script>
<script src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>

<script type="text/javascript">
	$(function() {
		$("#compose").validate();
	});

	function selectFields1(id, nama, no, fraksi) {
		$('#id_anggota').val(id);
		$('#nama_anggota').val(nama);
		$('#no_anggota').val(no);
		$('#fraksi_anggota').val(fraksi);
		$.facebox.close();
	}

	function ClearFields1() {
		document.getElementById("id_anggota").value = "";
		document.getElementById("nama_anggota").value = "";
		document.getElementById("no_anggota").value = "";
		document.getElementById("fraksi_anggota").value = "";
	}
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?= $this->avatar; ?> Edit Denah Tempat Duduk</h1>
	<div class="header_nav_links"><a href="/sidang/denah-duduk">Back to Daftar Denah Tempat Duduk</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label>Sesi</label>
			<input class="required" type="text" id="id_sidang" autocomplete="disable" name="id_sidang" value="<?= $this->row->id_sidang; ?>"/>
			<font color="red">*</font>
		</p>

		<p>
			<label>Seat</label>
			<input type="text" id="seat" autocomplete="disable" name="seat" value="<?= $this->row->seat; ?>" />
			<font color="red">*</font>
		</p>

		<p>
			<label>Kode</label>
			<input type="text" id="kode" autocomplete="disable" name="kode" value="<?= $this->row->kode; ?>" />
			<font color="red">*</font>
		</p>

		<p>
			<label>Blok</label>
			<input type="text" id="blok" autocomplete="disable" name="blok" value="<?= $this->row->blok; ?>" />
			<font color="red">*</font>
		</p>

		<p>
			<label>Baris</label>
			<input type="text" id="baris" autocomplete="disable" name="baris" value="<?= $this->row->baris; ?>" />
			<font color="red">*</font>
		</p>
		<p>
			<label>Kursi</label>
			<input type="text" id="kursi" autocomplete="disable" name="kursi" value="<?= $this->row->kursi; ?>" />
			<font color="red">*</font>
		</p>

		<!-- <p>
			<label>Nama Anggota</label>
			<input type="text" id="nama_anggota" autocomplete="disable" name="nama_anggota" value="<?= $this->row->nama_anggota; ?>" />
			<input type="hidden" id="id_anggota" autocomplete="disable" name="id_anggota" value="<?= $this->row->id_anggota; ?>" />
			<input type="button" value="..." id="btnAnggota" onclick="jQuery.facebox({ ajax: '/sidang/denah-duduk/search-anggota'});" />
			<input type="button" onclick="ClearFields1();" value="Clear" />
			<font color="red">*</font>
		</p> -->

		<p>
			<label>No Anggota</label>
			<input type="text" id="no_anggota" autocomplete="disable" name="no_anggota" value="<?= $this->row->no_anggota; ?>" />
			<font color="red">*</font>
		</p>

		<p>
			<label>Fraksi Anggota</label>
			<select id="fraksi_anggota" name="fraksi_anggota" style="width: 295px; font-size: 12.5px; border: 1px solid lightblue; padding-left: 0px;">
				<option value="Fraksi Partai Amanat Nasional" <?php if ($this->row->fraksi_anggota == "Fraksi Partai Amanat Nasional") echo "selected"; ?>>Fraksi Partai Amanat Nasional</option>

				<option value="Fraksi Partai Demokrat" <?php if ($this->row->fraksi_anggota == "Fraksi Partai Demokrat") echo "selected"; ?>>Fraksi Partai Demokrat</option>

				<option value="Fraksi Partai NasDem" <?php if ($this->row->fraksi_anggota == "Fraksi Partai NasDem") echo "selected"; ?>>Fraksi Partai NasDem</option>

				<option value="Fraksi Partai Golongan Karya" <?php if ($this->row->fraksi_anggota == "Fraksi Partai Golongan Karya") echo "selected"; ?>>Fraksi Partai Golongan Karya</option>

				<option value="Fraksi Partai Demokrasi Indonesia Perjuangan" <?php if ($this->row->fraksi_anggota == "Fraksi Partai Demokrasi Indonesia Perjuangan") echo "selected"; ?>>Fraksi Partai Demokrasi Indonesia Perjuangan</option>
				
				<option value="Fraksi Partai Gerakan Indonesia Raya" <?php if ($this->row->fraksi_anggota == "Fraksi Partai Gerakan Indonesia Raya") echo "selected"; ?>>Fraksi Partai Gerakan Indonesia Raya</option>

				<option value="Fraksi Partai Kebangkitan Bangsa" <?php if ($this->row->fraksi_anggota == "Fraksi Partai Kebangkitan Bangsa") echo "selected"; ?>>Fraksi Partai Kebangkitan Bangsa</option>

				<option value="Fraksi Partai Keadilan Sejahtera" <?php if ($this->row->fraksi_anggota == "Fraksi Partai Keadilan Sejahtera") echo "selected"; ?>>Fraksi Partai Keadilan Sejahtera</option>

				<option value="Fraksi Partai Persatuan Pembangunan" <?php if ($this->row->fraksi_anggota == "Fraksi Partai Persatuan Pembangunan") echo "selected"; ?>>Fraksi Partai Persatuan Pembangunan</option>

				<option value="Dewan Perwakilan Daerah" <?php if ($this->row->fraksi_anggota == "Dewan Perwakilan Daerah") echo "selected"; ?>>Dewan Perwakilan Daerah</option>
			</select>
			<font color="red">*</font>
		</p>

		<p>
			<label>Lembaga</label>
			<input type="text" id="lembaga" autocomplete="disable" name="lembaga" value="<?= $this->row->lembaga; ?>" />
			<font color="red">*</font>
		</p>

		<p>
			<label>Link Undangan</label>
			<input readonly type="text" name="undangan" value="https://belajar.dpr.go.id/sidang/index/seat/no-anggota/<?= strtolower(trim($this->row->no_anggota)) ?>/sesi/<?= $this->row->id_sidang ?>">
			<font color="red">*</font>
		</p>

		<input type="hidden" name="id" value="<?= $this->row->id; ?>" />

		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class="" /></label><a href="/sidang/denah-duduk" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>

<script>
  function updateUndanganLink() {
    var id_sidang = document.getElementById("id_sidang").value;
    var no_anggota = document.getElementById("no_anggota").value;
    var undanganLink = document.getElementsByName("undangan")[0];

    undanganLink.value = "https://belajar.dpr.go.id/sidang/index/seat/no-anggota/" + no_anggota + "/sesi/" + id_sidang;
  }

  // Memanggil fungsi updateUndanganLink saat nilai input berubah
  document.getElementById("id_sidang").addEventListener("input", updateUndanganLink);
  document.getElementById("no_anggota").addEventListener("input", updateUndanganLink);
</script>
