<script type="text/javascript">
$(function(){	
	$("#table_facebox")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager2"), 
							output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
							fixedHeight: true, 
							removeRows: false, 
							cssGoto: '.gotoPage' });
});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?> Anggota</h1>
</div>
<div class="clear"></div>
<br>

<? if (count($this->rows) > 0) { ?>
	<?=$this->pager2;?>

	<table cellspacing="1" cellpadding="6" width="100%" class="tablesorter" id="table_facebox">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nama</th>
				<th>Nomor</th>
				<th>Fraksi</th>
				<th>Aksi</th>
			</tr>
		</thead>
		<tbody>
			<?
			$i = 1;
			foreach($this->rows as $row)
			{
				echo '<tr>';
				echo '<td align="center">' . $row->id . '</td>';
				echo '<td>' . $row->nama . '</td>';
				echo '<td align="center">' . $row->nomor . '</td>';
				echo '<td>' . $row->unit_kerja . '</td>';
				echo '<td align="center"><a href="javascript:selectFields1(\'' . $row->id . '\', \'' . str_replace("'", "\'", $row->nama) . '\', \'' . $row->nomor . '\', \'' . $row->unit_kerja . '\')">PILIH</a></td>';
				echo '</tr>';

				$i++;
			}	
			?>	
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>