<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsbarcode/3.11.3/JsBarcode.all.min.js"></script>
<script src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://berkas.dpr.go.id/mooc/assets/css/denah-tempat-duduk.css">


<!-- pdf -->
<div id="isi-pdf" class="isi-pdf">
	<img class="img-bg" src="https://berkas.dpr.go.id/mooc/assets/images/bg-undangan1.jpg" alt="bg-undangan1">
	<div class="info-pdf">
		<p class="m-0 mb-2 text-center fs-2 fw-bold" style="width: 100% !important;">Undangan Rapat RAPBN</p>
		<p class="m-0 fs-7">Nama : <?= $this->undangan->nama_anggota ?></p>
		<p class="m-0 fs-7">Sesi : <?= $this->undangan->id_sidang ?></p>
		<p class="m-0 fs-7">Nomor : <?= $this->undangan->no_anggota ?></p>
		<p class="m-0 fs-7">Fraksi : <?= $this->undangan->fraksi_anggota ?></p>
		<p class="m-0 fs-7">Lembaga : <?= $this->undangan->lembaga ?></p>
		<p class="m-0 fs-7">Kode : <?= $this->undangan->kode ?></p>
	</div>

	<!-- barcode -->
	<div class="content-undangan">
		<div id="qrcode-undangan"></div>
	</div>

	<div class="info-link">
		<p>Link Undangan : <a href="https://belajar.dpr.go.id/sidang/index/seat/no-anggota/<?= strtolower(trim($this->undangan->no_anggota)) ?>/sesi/<?= $this->undangan->id_sidang ?>">https://belajar.dpr.go.id/sidang/index/seat/no-anggota/<?= strtolower(trim($this->undangan->no_anggota)) ?>/sesi/<?= $this->undangan->id_sidang ?></a>
		</p>
	</div>
	<!-- end barcode -->
</div>
<div class="m-auto mb-5" style="max-width: 40vw;">
	<a href="/sidang/index/file-undangan/no-anggota/<?= $this->undangan->id ?>" id="download-button" class="download-button rounded-2 border border-0 py-2 px-2 fw-bold text-light text-decoration-none" style="background-color: #FE182A;" target="blank"><i class="bi bi-filetype-pdf fs-4 me-1 text-light"></i>Download as PDF</a>
</div>
<!-- end pdf -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<script>
	// barcode
    $(document).ready(function() {
        let qrcode = null;

        // let inputText = $("#input-qr-undangan");
        let generateQRCode = () => {
			let text = "<?= $this->undangan->undangan ?>";

            // Timpa QR sebelumnya jika ada
            if (qrcode) {
                qrcode.clear();
                qrcode.makeCode(text);
            } else {
                qrcode = new QRCode(document.getElementById("qrcode-undangan"), {
                    text: text,
                    width: 250,
                    height: 250,
                });
            }

			let qrCodeElement = document.getElementById("qrcode-undangan");
    		qrCodeElement.style.border = "5px solid white";
        };

        generateQRCode();
	});
    // end barcode

	// pdf
	// const button = document.getElementById('download-button');
	// button.addEventListener('click', generatePDF);
	
	// function generatePDF() {
	// 	const isiPdf = document.getElementById('isi-pdf');
	// 	const fileName = 'Undangan_Rapat_RAPBN.pdf';

	// 	html2canvas(isiPdf, {
	// 		scrollX: 0,
	// 		scrollY: -window.scrollY
	// 	}).then(canvas => {
	// 		const pdf = new window.jspdf.jsPDF('p', 'mm', 'a4');
	// 		const imgData = canvas.toDataURL('image/jpeg', 1.0);
	// 		pdf.addImage(imgData, 'JPEG', 0, 0, 210, 297);
	// 		pdf.save(fileName);
	// 	});
	// }
	// end pdf
</script>

